loki:
  persistence:
    enabled: false
  service:
    type: ClusterIP
  ingress:
    enabled: true
    ingressClassName: "nginx"
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    hosts:
      - host: "loki.example.com"
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: loki-tls
        hosts:
          - "loki.example.com"

promtail:
  config:
    clients:
      - url: http://loki:3100/loki/api/v1/push
    positions:
      filename: /tmp/positions.yaml
    scrape_configs:
      - job_name: kubernetes-pods-django
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
            regex: django-service
            action: keep
  serviceAccount:
    create: true
  daemonset:
    enabled: true
  podAnnotations: {}
  extraArgs:
    - --client.url=http://loki:3100/loki/api/v1/push
