apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prometheus.fullname" . }}-config
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}
data:
  prometheus.yml: |
    global:
      scrape_interval: {{ .Values.prometheus.global.scrape_interval }}
      evaluation_interval: {{ .Values.prometheus.global.evaluation_interval }}
    scrape_configs:
      {{- toYaml .Values.prometheus.scrape_configs | nindent 6 }}
