apiVersion: v2
name: prometheus
description: Prometheus metrics monitoring
type: application
version: 1.0.0
appVersion: "15.0.0"
home: https://prometheus.io
sources:
  - https://github.com/prometheus/prometheus
maintainers:
  - name: Helm Charts
    email: charts@example.com
