apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sentry.fullname" . }}
  labels:
    {{- include "sentry.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "sentry.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sentry.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
      - name: db-migrate
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ['sentry', 'upgrade', '--noinput']
        env:
          {{- range $key, $value := .Values.sentry.environment }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 9000
          protocol: TCP
        command: ['sentry', 'run', 'web']
        env:
          {{- range $key, $value := .Values.sentry.environment }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
        livenessProbe:
          httpGet:
            path: /auth/login/
            port: http
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /auth/login/
            port: http
          initialDelaySeconds: 60
          periodSeconds: 10
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        {{- if .Values.persistence.enabled }}
        volumeMounts:
        - name: data
          mountPath: /data
        {{- end }}
      {{- if .Values.persistence.enabled }}
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ include "sentry.fullname" . }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
